Vagrant.configure("2") do |config|
  config.hostmanager.enabled = true 
  config.hostmanager.manage_host = true
  
### jenkins vm  ####
  config.vm.define "jenkins" do |jenkins|
    jenkins.vm.box = "ubuntu/jammy64"
    jenkins.vm.hostname = "jenkins.lab"
    jenkins.vm.network "private_network", ip: "192.168.56.5"
    jenkins.vm.provider "virtualbox" do |vb|
     vb.memory = "1600"
   end

  end
  
### sonarqube vm  #### 
  config.vm.define "sonarqube" do |sonarqube|
    sonarqube.vm.box = "ubuntu/jammy64"
    sonarqube.vm.hostname = "sonarqube.lab"
    sonarqube.vm.network "private_network", ip: "192.168.56.15"
    sonarqube.vm.provider "virtualbox" do |vb|
     vb.memory = "2272"
   end
  end

  ### Nexus VM  #### 
  config.vm.define "nexus" do |nexus|
    nexus.vm.box = "eurolinux-vagrant/centos-stream-9"
    nexus.vm.hostname = "nexus.lab"
    nexus.vm.network "private_network", ip: "192.168.56.25"
    nexus.vm.provider "virtualbox" do |vb|
     vb.memory = "2272"
   end
  end
  

end
